apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  password: postgresSecretpw
---
apiVersion: v1
kind: Secret
metadata:
  name: auction-secret
type: Opaque
stringData:
  rabbitUsername: rabbit
  rabbitPassword: rabbit
  connectionString: Server=postgres-clusterip:5432;User Id=postgres;Password=postgresSecretpw;Database=auctions
