apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  password: postgresSecretPw
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbit-secret
type: Opaque
stringData:
  username: rabbit
  password: rabbitSecretPw
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  username: mongo
  password: mongoSecretPw
---
apiVersion: v1
kind: Secret
metadata:
  name: auction-secret
type: Opaque
stringData:
  rabbitUsername: rabbit
  rabbitPassword: rabbitSecretPw
  connectionString: Server=postgres-clusterip:5432;User Id=postgres;Password=postgresSecretPw;Database=auctions
