apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-svc
spec:
  selector:
    matchLabels:
      app: auction-svc
  template:
    metadata:
      labels:
        app: auction-svc
    spec:
      containers:
      - name: auction-svc
        image: knphilip/bidwheels-auction-svc
        imagePullPolicy: Always
        env:
          - name: RabbitMQ__Host
            value: rabbitmq-clusterip
          - name: RabbitMQ__Username
            valueFrom:
              secretKeyRef:
                name: auction-secret
                key: rabbitUsername
          - name: RabbitMQ__Password
            valueFrom:
              secretKeyRef:
                name: auction-secret
                key: rabbitPassword
          - name: ConntectionStrings__Default
            valueFrom:
              secretKeyRef:
                name: auction-secret
                key: connectionString
          - name: IdentityServiceUrl
            value: https://id.sample-website.com
          - name: Kestrel__Endpoints__Grpc__Protocols
            value: Http2
          - name: Kestrel__Endpoints__Grpc__Url
            value: http://+:7777
          - name: Kestrel__Endpoints__WebApi__Protocols
            value: Http1
          - name: Kestrel__Endpoints__WebApi__Protocols
            value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: auction-clusterip
spec:
  type: ClusterIP
  selector:
    app: auction-svc
  ports:
  - port: 80
    targetPort: 80
    name: web
  - port: 7777
    targetPort: 7777
    name: grpc
