apiVersion: apps/v1
kind: Deployment
metadata:
  name: bid-svc
spec:
  selector:
    matchLabels:
      app: bid-svc
  template:
    metadata:
      labels:
        app: bid-svc
    spec:
      containers:
      - name: bid-svc
        image: knphilip/bid-search-svc
        imagePullPolicy: Never
        env:
          - name: RabbitMQ__Host
            value: rabbitmq-clusterip
          - name: RabbitMQ__Username
            valueFrom:
              secretKeyRef:
                name: bid-secret
                key: rabbitUsername
          - name: RabbitMQ__Password
            valueFrom:
              secretKeyRef:
                name: bid-secret
                key: rabbitPassword
          - name: ConntectionStrings__BidDbConnection
            valueFrom:
              secretKeyRef:
                name: bid-secret
                key: connectionString
          - name: IdentityServiceUrl
            value: https://id.sample-website.com
          - name: GrpcAuction
            value: http://auction-clusterip:7777
---
apiVersion: v1
kind: Service
metadata:
  name: bid-clusterip
spec:
  type: ClusterIP
  selector:
    app: bid-svc
  ports:
  - port: 80
    targetPort: 80
