apiVersion: apps/v1
kind: Deployment
metadata:
  name: notify-svc
spec:
  selector:
    matchLabels:
      app: notify-svc
  template:
    metadata:
      labels:
        app: notify-svc
    spec:
      containers:
      - name: notify-svc
        image: knphilip/bidwheels-notify-svc
        imagePullPolicy: Always
        env:
          - name: RabbitMQ__Host
            value: rabbitmq-clusterip
          - name: RabbitMQ__Username
            valueFrom:
              secretKeyRef:
                name: notify-secret
                key: rabbitUsername
          - name: RabbitMQ__Password
            valueFrom:
              secretKeyRef:
                name: notify-secret
                key: rabbitPassword
---
apiVersion: v1
kind: Service
metadata:
  name: notify-clusterip
spec:
  type: ClusterIP
  selector:
    app: notify-svc
  ports:
  - port: 80
    targetPort: 80
