global using Xunit;
global using MassTransit;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.AspNetCore.Mvc.Testing;
global using Microsoft.AspNetCore.TestHost;
global using Mongo2Go;
global using MongoDB.Driver;
global using MongoDB.Entities;
global using SearchService.Models;