name: Apply Kubernetes

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Save DigitalOcean kubeconfig
      run: doctl kubernetes cluster kubeconfig save bidwheels
    - name: Apply Kubernetes manifests
      run: kubectl apply -f infrastructure/K8S && kubectl apply -f infrastructure/prod-k8s