name: Deploy Identity Service

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/IdentityService/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Build and push the Docker image
      uses: knphilip/actions/dockerfile-push@main
      with:
        tags: knphilip/bidwheels-identity-svc:latest
        file: src/IdentityService/Dockerfile
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}