name: Deploy Auction Service

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/AuctionService/**'

env:
  REGISTRY_IMAGE: knphilip/bidwheels-auction-svc
  DOCKERFILE: src/AuctionService/Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build and push the Docker image
      uses: knphilip/actions/dockerfile-push@main
      with:
        context: "{{defaultContext}}"
        tags: ${{ env.REGISTRY_IMAGE }}:latest
        file: ${{ env.DOCKERFILE }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}